### ISSUE TITLE
Search/replace is off by a few characters

### ISSUE THREAD

**Issue by dhilditch** [padolsey/findAndReplaceDOMText#40]
I'm trying your code to do a search and replace on some html where I need to retain the events. I don't have access server side (and won't) so this would be ideal but for some reason the replace is off:

See this jsfiddle:

https://jsfiddle.net/py1t60L4/1/

Note: The hyperlink after the search/replace runs has transposed backwards a little bit.

I got as far as finding out that getPortionReplacementNode has a matchIndex value but this never gets passed so its undefined. I tried bubbling this through but then it's always 0 and didn't make any difference.

Maybe you can figure it out?

**Comment by padolsey** [comment]
The issue here is that the replacement DOM text is being transposed into the DOM hierarchy of the match.

The `$2` in your replacement is not saying "*take $2's DOM and replace the entire match's DOM with it*", but instead it's saying "*take $2's text and transpose it into the match's DOM*".

So, e.g. (http://jsfiddle.net/cjb5bpqd/), in the structure:

```html
<div>
    foo<em>111</em>
    baz<strong>999</strong>
</div>
```

If foo111 is replaced with baz999:

```js
findAndReplaceDOMText(document.querySelector('div'), {
    find: /foo111\s*(baz999)/g,
    replace: '$1'
});
``` 

You will end up with:

```html
<div>
    baz<em>999</em>
    <strong></strong>
</div>
```
So, the DOM structure is left in-tact, and the replacement text is transposed into it, in this case it results in a result that's not very intuitive.

The reason that we can't just replace the DOM wholesale with the DOM of `$1` or `$2` (or whatever) is because matches can exist across element boundaries. So, imagine if the `$2` DOM is between the brackets here (*baz123*):

```html
<span>foo bar (baz</span>123)
```

baz123 as a piece of DOM cannot be transposed elsewhere since it is not a valid DOM fragment, but as simple text it can be transposed.

To be honest, I'd love to find a way to make this work intuitively, but the edge cases are quite hard to get around. I'll keep thinking on this as I do believe it should work without difficulty.

What I would do in your case is not do a replacement but simply remove the stuff I don't want, so:

```js
// Remove "....{text}..":
findAndReplaceDOMText(jQuery('body')[0], {
  find: /\.{4}(.*?)\.\./g,
  replace: ' '
});
// Remove "...." at the end:
findAndReplaceDOMText(jQuery('body')[0], {
  find: /\.{4}$/g,
  replace: ' ',
  preset: 'prose'
});	
```
